name: Deploy helm chart to EKS
description: 'Deploy helm chart to eks'
inputs:
  deployment_name:
    required: false
    default: ${{ github.event.repository.name }}
  helm_namespace:
    required: false
    default: default
  helm_chart_directory:
    required: true
  image_repository:
    required: true
  image_tag:
    required: true
  execute_helm_test:
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - run: echo "DEPLOYMENT_NAME_LOWERCASE=$(echo ${{ inputs.deployment_name }} | awk '{print tolower($0)}')" >> $GITHUB_ENV
      shell: bash
    - run: echo "IMAGE_REPOSITORY_LOWERCASE=$(echo ${{ inputs.image_repository }} | awk '{print tolower($0)}')" >> $GITHUB_ENV
      shell: bash
    - run: |
          helm upgrade --install -n ${{ inputs.helm_namespace }} --create-namespace $DEPLOYMENT_NAME_LOWERCASE ${{ inputs.helm_chart_directory }} \
          --set image.repository=$IMAGE_REPOSITORY_LOWERCASE \
          --set image.tag=${{ inputs.image_tag }}
          --set configMap.data.work_environment=${{ inputs.helm_namespace }}
      shell: bash
    - run: sleep 30 && helm test $DEPLOYMENT_NAME_LOWERCASE -n ${{ inputs.helm_namespace }}
      if: inputs.execute_helm_test == 'true'
      shell: bash
