name: My App to EKS with Helm Workflow

on:
  push:
    branches: [ master ]  
  pull_request:
    branches: [ master ]
  
env:
  NODE_VERSION: 18
  
jobs:
  build-and-test:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Clean install modules
        run: npm ci
      - name: Run build
        run: npm run build --if-present
      - name: Execute jest test with coverage
        run: npx jest --coverage
      
  eslint:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Clean install  moduels
        run: npm ci
      - name: Eslint
        run: npx eslint .
